---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values (slide 21)

ggplot(ratings, aes(x = rating)) +
    geom_histogram(bins = 10) + 
  scale_y_continuous(label = comma)
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group

#aggregate(ratings$rating, list(movie = ratings$movie_id), mean) %>% 
 # summarize(num_ratings = n()) %>% View

ratings %>% group_by(movie_id) %>% summarize(avg_rating = mean(rating), num_ratings = n())
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
ratings %>% group_by(movie_id) %>% summarise(num_ratings = n()) %>%
  ggplot(aes(x = num_ratings)) + geom_histogram() + scale_x_log10(label = comma)
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie (slide 23)
# hint: try geom_histogram and geom_density
ratings %>% group_by(movie_id) %>% summarize(avg_rating = mean(rating)) %>% ggplot(aes(x = avg_rating)) + geom_histogram() + geom_density(fill = "grey") +
    xlab('Average rating') 

ratings %>% group_by(movie_id) %>% summarize(avg_rating = mean(rating)) %>% ggplot(aes(x = avg_rating)) + geom_density(fill = "grey") +
    xlab('Average rating') +
    ylab('Density')
```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves (slide 25)
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity
ratings %>% group_by(movie_id) %>% summarise(num_ratings = n()) %>% arrange(rank(desc(num_ratings))) %>% mutate(rank = row_number(), frac_movies =  (cumsum(num_ratings))/sum(num_ratings)) %>% 
  ggplot(aes(x= rank, y = frac_movies))+ geom_line() +
  xlab('Movie Rank') + ylab('CDF')
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
ratings %>% group_by(user_id) %>% summarize(avg_rating = mean(rating), num_ratings = n())
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>% group_by(user_id) %>% summarize(num_ratings = n()) %>%
  ggplot(aes(x = num_ratings)) + geom_histogram() + scale_x_log10(label = comma) +
  ylab('Number of Users') + xlab('Number of Ratings')
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

movie_pop <- group_by(ratings, movie_id) %>% summarise(num_ratings = n()) %>% arrange(desc(num_ratings)) %>% mutate(rank = row_number()) 

movie_ranks <- inner_join(ratings, movie_pop) 

cutoff_100 <- movie_ranks %>% group_by(user_id) %>% summarize(cutoff = max(rank))

cutoff_90 <- movie_ranks %>% group_by(user_id) %>% summarize(cutoff = quantile(rank,0.9))

df_cutoff_100 <- cutoff_100 %>% group_by(cutoff) %>% summarise(num_users = n()) %>% arrange(rank(cutoff)) %>% mutate(frac_users = (cumsum(num_users))/sum(num_users), set_level = "100%") 

df_cutoff_90 <- cutoff_90 %>% group_by(cutoff) %>% summarise(num_users = n()) %>% arrange(rank(cutoff)) %>% mutate(frac_users = (cumsum(num_users))/sum(num_users), set_level = "90%")

df <- bind_rows(df_cutoff_90, df_cutoff_100) 
  

df %>% ggplot(aes(x=cutoff, y = frac_users, color = set_level))+ geom_line() +
  xlab('Inventory Size') + ylab('% of Users Satisfied')
```
