---
title: 'Decision Trees: Toy Example and Detecting Fradulent Transactions'
author: "Amanda Rodriguez"
date: "July 2, 2018"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
titanic_train <- read.csv("../week3/titanic_train.csv") 

# What percentage of passengers in our data set survived?
titanic_train %>% summarise(pass_survived = mean(Survived))
```

```{r}
# Which variables do you think may be good predictors of the survival on the Titanic? Document your exploration. (Hint: You may want to turn the Survived variable into a factor using the factor() function.)
# age, gender, Pclass
titanic_train %>% glm(formula = Survived ~ Sex * Age + as.factor(Pclass), family = "binomial")
 
```

```{r}
# Estimate a decision tree predicting survival using age and sex as predictors. Describe your results.
tree(as.factor(Survived) ~ Age + Sex,titanic_train) %>% summary()
```

```{r}
# Estimate a decision tree using age, sex and passenger class. Describe your results.
tree(as.factor(Survived) ~ Age + Sex +as.factor(Pclass),titanic_train) %>% summary()
plot(tree(as.factor(Survived) ~ Age + Sex + as.factor(Pclass),titanic_train))
text(tree(as.factor(Survived) ~ Age + Sex + as.factor(Pclass),titanic_train),pretty =0)
```

```{r}
# Estimate your own decision tree with your own set of predictors (you are, of course, free to include the predictors we used above). How accurate is your model on the training data? How does it compare to the models above?
tree_model <- tree(as.factor(Survived) ~ Age + Sex + as.factor(Pclass) + SibSp + Parch,titanic_train)
summary(tree_model)
plot(tree(as.factor(Survived) ~ Age + Sex + as.factor(Pclass)+ SibSp + Parch,titanic_train))
text(tree(as.factor(Survived) ~ Age + Sex + as.factor(Pclass)+ SibSp + Parch,titanic_train),pretty =0)
```

```{r}
# Download test data. This is the test data from Kaggle, we actually don't know the true fate of the passengers in this data set. Use this data to make predictions for these passengers.
test <- read.csv("../week4/test.csv")
test$Survived_pred <- predict(tree_model,test,type="class")
```